/**
   * This file is autogenerated.
   * You should not edit it manually or your changes might be overwritten.
   */
  import { GenericModulesDeclaration } from "~~/utils/scaffold-move/module";

  const deployedModules = {
    176:{
  "records": {
    "bytecode": "0xa11ceb0b0700000a0b01000a020a0c03162b04410205432b076e9e01088c024010cc02490a9503130ca803ad010dd504020000010401090106010e00010f000103070000070f00000800010001020a00020001000b05010001030c01060001000d08010001040f090a0100010010020b0001050301060c00010501080001080203060c0a0801080101030203080002060c0302070a090003010900010a0800077265636f726473065265636f7264086b6579776f72647306537472696e6706737472696e670b6465736372697074696f6e0974696d657374616d70075265636f72647304696e6974067369676e65720a616464726573735f6f660a6164645f7265636f72640b6e6f775f7365636f6e64730d64656c6574655f7265636f726406766563746f720672656d6f76650f6765745f616c6c5f7265636f7264734fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603000000000000000000000000000000000000000000000000000000000000000114636f6d70696c6174696f6e5f6d65746164617461090003322e3003322e31126170746f733a3a6d657461646174615f7631160000010f6765745f616c6c5f7265636f726473010100000203020a08010508010603020201000a0800000104010104100a0011012901030505090a0011012c01014003000000000000000012010c010b000b012d0102020100010107160a0011012901041211030c030b0011012a010b010b020b0312000c040f000b044403020b000106140000000000000027040100010101100a0011012901040c0b0011012a010f000b01380001020b0001061400000000000000270601000101010a0a00290104080b002b011000140206140000000000000027010000",
    "abi": {
      "address": "0x4fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603",
      "name": "records",
      "friends": [],
      "exposed_functions": [
        {
          "name": "init",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer"
          ],
          "return": []
        },
        {
          "name": "add_record",
          "visibility": "public",
          "is_entry": false,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "vector<0x1::string::String>",
            "0x1::string::String"
          ],
          "return": []
        },
        {
          "name": "delete_record",
          "visibility": "public",
          "is_entry": false,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "u64"
          ],
          "return": []
        },
        {
          "name": "get_all_records",
          "visibility": "public",
          "is_entry": false,
          "is_view": true,
          "generic_type_params": [],
          "params": [
            "address"
          ],
          "return": [
            "vector<0x4fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603::records::Record>"
          ]
        }
      ],
      "structs": [
        {
          "name": "Record",
          "is_native": false,
          "is_event": false,
          "abilities": [
            "copy",
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "keywords",
              "type": "vector<0x1::string::String>"
            },
            {
              "name": "description",
              "type": "0x1::string::String"
            },
            {
              "name": "timestamp",
              "type": "u64"
            }
          ]
        },
        {
          "name": "Records",
          "is_native": false,
          "is_event": false,
          "abilities": [
            "copy",
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "records",
              "type": "vector<0x4fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603::records::Record>"
            }
          ]
        }
      ]
    }
  },
  "user_info": {
    "bytecode": "0xa11ceb0b0700000a0901000802080803101e052e1e074cc001088c024010cc024c0a98031e0cb6037300000104010e001000010f0001030700000d00010001020f0002000103110001000100120301000100130204000101060c0001050a060c08010801080108010801080108010801080101080009757365725f696e666f0855736572496e666f0976616c69645f6d736706537472696e6706737472696e67046e616d65037365780d646174655f6f665f626972746809656475636174696f6e096f6375706174696f6e0f636f756e73656c696e67686f7572730c6f7269656e746174696f6e730a746563686e69717565730664656c657465067369676e65720a616464726573735f6f66077265636f72647304696e6974087265676973746572126765745f757365725f696e666f5f73656c664fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603000000000000000000000000000000000000000000000000000000000000000114636f6d70696c6174696f6e5f6d65746164617461090003322e3003322e31126170746f733a3a6d657461646174615f763119000001126765745f757365725f696e666f5f73656c660101000002090208010508010608010708010808010908010a08010b08010c08010001040100010c0a0011012900030505090a0011012c00010b001102020301040100041a0a0011012900030505090a0011012c00010b010b020b030b040b050b060b070b080b0912000c0a0a000b0a2d000b00110202040100010001090a00290004070b002b001402060a000000000000002700",
    "abi": {
      "address": "0x4fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603",
      "name": "user_info",
      "friends": [],
      "exposed_functions": [
        {
          "name": "delete",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer"
          ],
          "return": []
        },
        {
          "name": "register",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        },
        {
          "name": "get_user_info_self",
          "visibility": "public",
          "is_entry": false,
          "is_view": true,
          "generic_type_params": [],
          "params": [
            "address"
          ],
          "return": [
            "0x4fc3a3c706b0b70465194113bce4f9b0f42a227b17f2e3eb4bf5b076eb59a603::user_info::UserInfo"
          ]
        }
      ],
      "structs": [
        {
          "name": "UserInfo",
          "is_native": false,
          "is_event": false,
          "abilities": [
            "copy",
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "valid_msg",
              "type": "0x1::string::String"
            },
            {
              "name": "name",
              "type": "0x1::string::String"
            },
            {
              "name": "sex",
              "type": "0x1::string::String"
            },
            {
              "name": "date_of_birth",
              "type": "0x1::string::String"
            },
            {
              "name": "education",
              "type": "0x1::string::String"
            },
            {
              "name": "ocupation",
              "type": "0x1::string::String"
            },
            {
              "name": "counselinghours",
              "type": "0x1::string::String"
            },
            {
              "name": "orientations",
              "type": "0x1::string::String"
            },
            {
              "name": "techniques",
              "type": "0x1::string::String"
            }
          ]
        }
      ]
    }
  }
},
  } as const;

  export default deployedModules satisfies GenericModulesDeclaration;